In [15]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [16]:
#pd.set_option('display.max_columns', None)
ata_confirmed=pd.read_csv('time_series_covid19_confirmed_global.csv')
data_death=pd.read_csv('time_series_covid19_deaths_global.csv')
data_recovered=pd.read_csv('time_series_covid19_recovered_global.csv')

print(data_confirmed.shape)
print(data_death.shape)
print(data_recovered.shape)

data_confirmed.head()

(271, 350)
(271, 350)
(256, 350)

,Province/State,Country/Region,Lat,Long,1/22/20,1/23/20,1/24/20,1/25/20,1/26/20,1/27/20,1/28/20,1/29/20,1/30/20,1/31/20,2/1/20,2/2/20,2/3/20,2/4/20,2/5/20,2/6/20,2/7/20,2/8/20,2/9/20,2/10/20,2/11/20,2/12/20,2/13/20,2/14/20,2/15/20,2/16/20,2/17/20,2/18/20,2/19/20,2/20/20,2/21/20,2/22/20,2/23/20,2/24/20,2/25/20,2/26/20,2/27/20,2/28/20,2/29/20,3/1/20,3/2/20,3/3/20,3/4/20,3/5/20,3/6/20,3/7/20,3/8/20,3/9/20,3/10/20,3/11/20,3/12/20,3/13/20,3/14/20,3/15/20,3/16/20,3/17/20,3/18/20,3/19/20,3/20/20,3/21/20,3/22/20,3/23/20,3/24/20,3/25/20,3/26/20,3/27/20,3/28/20,3/29/20,3/30/20,3/31/20,4/1/20,4/2/20,4/3/20,4/4/20,4/5/20,4/6/20,4/7/20,4/8/20,4/9/20,4/10/20,4/11/20,4/12/20,4/13/20,4/14/20,4/15/20,4/16/20,4/17/20,4/18/20,4/19/20,4/20/20,4/21/20,4/22/20,4/23/20,4/24/20,4/25/20,4/26/20,4/27/20,4/28/20,4/29/20,4/30/20,5/1/20,5/2/20,5/3/20,5/4/20,5/5/20,5/6/20,5/7/20,5/8/20,5/9/20,5/10/20,5/11/20,5/12/20,5/13/20,5/14/20,5/15/20,5/16/20,5/17/20,5/18/20,5/19/20,5/20/20,5/21/20,5/22/20,5/23/20,5/24/20,5/25/20,5/26/20,5/27/20,5/28/20,5/29/20,5/30/20,5/31/20,6/1/20,6/2/20,6/3/20,6/4/20,6/5/20,6/6/20,6/7/20,6/8/20,6/9/20,6/10/20,6/11/20,6/12/20,6/13/20,6/14/20,6/15/20,6/16/20,6/17/20,6/18/20,6/19/20,6/20/20,6/21/20,6/22/20,6/23/20,6/24/20,6/25/20,6/26/20,6/27/20,6/28/20,6/29/20,6/30/20,7/1/20,7/2/20,7/3/20,7/4/20,7/5/20,7/6/20,7/7/20,7/8/20,7/9/20,7/10/20,7/11/20,7/12/20,7/13/20,7/14/20,7/15/20,7/16/20,7/17/20,7/18/20,7/19/20,7/20/20,7/21/20,7/22/20,7/23/20,7/24/20,7/25/20,7/26/20,7/27/20,7/28/20,7/29/20,7/30/20,7/31/20,8/1/20,8/2/20,8/3/20,8/4/20,8/5/20,8/6/20,8/7/20,8/8/20,8/9/20,8/10/20,8/11/20,8/12/20,8/13/20,8/14/20,8/15/20,8/16/20,8/17/20,8/18/20,8/19/20,8/20/20,8/21/20,8/22/20,8/23/20,8/24/20,8/25/20,8/26/20,8/27/20,8/28/20,8/29/20,8/30/20,8/31/20,9/1/20,9/2/20,9/3/20,9/4/20,9/5/20,9/6/20,9/7/20,9/8/20,9/9/20,9/10/20,9/11/20,9/12/20,9/13/20,9/14/20,9/15/20,9/16/20,9/17/20,9/18/20,9/19/20,9/20/20,9/21/20,9/22/20,9/23/20,9/24/20,9/25/20,9/26/20,9/27/20,9/28/20,9/29/20,9/30/20,10/1/20,10/2/20,10/3/20,10/4/20,10/5/20,10/6/20,10/7/20,10/8/20,10/9/20,10/10/20,10/11/20,10/12/20,10/13/20,10/14/20,10/15/20,10/16/20,10/17/20,10/18/20,10/19/20,10/20/20,10/21/20,10/22/20,10/23/20,10/24/20,10/25/20,10/26/20,10/27/20,10/28/20,10/29/20,10/30/20,10/31/20,11/1/20,11/2/20,11/3/20,11/4/20,11/5/20,11/6/20,11/7/20,11/8/20,11/9/20,11/10/20,11/11/20,11/12/20,11/13/20,11/14/20,11/15/20,11/16/20,11/17/20,11/18/20,11/19/20,11/20/20,11/21/20,11/22/20,11/23/20,11/24/20,11/25/20,11/26/20,11/27/20,11/28/20,11/29/20,11/30/20,12/1/20,12/2/20,12/3/20,12/4/20,12/5/20,12/6/20,12/7/20,12/8/20,12/9/20,12/10/20,12/11/20,12/12/20,12/13/20,12/14/20,12/15/20,12/16/20,12/17/20,12/18/20,12/19/20,12/20/20,12/21/20,12/22/20,12/23/20,12/24/20,12/25/20,12/26/20,12/27/20,12/28/20,12/29/20,12/30/20,12/31/20,1/1/21
0,NaN,Afghanistan,33.93911,67.709953,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,2,4,4,4,4,5,7,8,11,12,13,15,16,18,20,24,25,29,30,34,41,43,76,80,91,107,118,146,175,197,240,275,300,338,368,424,445,485,532,556,608,666,715,785,841,907,934,997,1027,1093,1177,1236,1331,1464,1532,1704,1830,1940,2127,2291,2470,2705,2895,3225,3393,3564,3781,4042,4403,4687,4968,5227,5640,6054,6403,6665,7073,7654,8146,8677,9219,10001,10585,11176,11834,12459,13039,13662,14528,15208,15753,16512,17270,18057,18972,19554,20345,20920,21462,22146,22894,23550,24106,24770,25531,26314,26878,27536,27882,28428,28837,29147,29471,29705,30165,30441,30606,30957,31228,31507,31826,32012,32314,32662,32941,33180,33374,33584,33898,34184,34356,34441,34595,34730,34984,35060,35219,35279,35453,35493,35605,35717,35918,35978,36026,36147,36253,36358,36463,36532,36665,36700,36701,36737,36773,36820,36928,37006,37046,37083,37153,37260,37336,37422,37497,37542,37590,37667,37710,37750,37852,37885,37944,37990,38045,38061,38103,38119,38130,38133,38155,38159,38193,38243,38288,38304,38324,38398,38494,38520,38544,38572,38606,38641,38716,38772,38815,38855,38872,38897,38919,39044,39074,39096,39145,39170,39186,39192,39227,39239,39254,39268,39285,39290,39297,39341,39422,39486,39548,39616,39693,39703,39799,39870,39928,39994,40026,40088,40141,40200,40287,40369,40510,40626,40687,40768,40833,40937,41032,41145,41268,41334,41425,41501,41633,41728,41814,41935,41975,42033,42159,42297,42463,42609,42795,42969,43035,43240,43468,43681,43924,44177,44363,44503,44706,44988,45174,45384,45600,45723,45844,46116,46274,46516,46718,46837,46837,47072,47306,47516,47716,47851,48053,48116,48229,48527,48718,48952,49161,49378,49621,49681,49817,50013,50190,50433,50655,50810,50886,51039,51280,51350,51405,51526,51526
1,NaN,Albania,41.15330,20.168300,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,10,12,23,33,38,42,51,55,59,64,70,76,89,104,123,146,174,186,197,212,223,243,259,277,304,333,361,377,383,400,409,416,433,446,467,475,494,518,539,548,562,584,609,634,663,678,712,726,736,750,766,773,782,789,795,803,820,832,842,850,856,868,872,876,880,898,916,933,946,948,949,964,969,981,989,998,1004,1029,1050,1076,1099,1122,1137,1143,1164,1184,1197,1212,1232,1246,1263,1299,1341,1385,1416,1464,1521,1590,1672,1722,1788,1838,1891,1962,1995,2047,2114,2192,2269,2330,2402,2466,2535,2580,2662,2752,2819,2893,2964,3038,3106,3188,3278,3371,3454,3571,3667,3752,3851,3906,4008,4090,4171,4290,4358,4466,4570,4637,4763,4880,4997,5105,5197,5276,5396,5519,5620,5750,5889,6016,6151,6275,6411,6536,6676,6817,6971,7117,7260,7380,7499,7654,7812,7967,8119,8275,8427,8605,8759,8927,9083,9195,9279,9380,9513,9606,9728,9844,9967,10102,10255,10406,10553,10704,10860,11021,11185,11353,11520,11672,11816,11948,12073,12226,12385,12535,12666,12787,12921,13045,13153,13259,13391,13518,13649,13806,13965,14117,14266,14410,14568,14730,14899,15066,15231,15399,15570,15752,15955,16212,16501,16774,17055,17350,17651,17948,18250,18556,18858,19157,19445,19729,20040,20315,20634,20875,21202,21523,21904,22300,22721,23210,23705,24206,24731,25294,25801,26211,26701,27233,27830,28432,29126,29837,30623,31459,32196,32761,33556,34300,34944,35600,36245,36790,37625,38182,39014,39719,40501,41302,42148,42988,43683,44436,45188,46061,46863,47742,48530,49191,50000,50637,51424,52004,52542,53003,53425,53814,54317,54827,55380,55755,56254,56572,57146,57727,58316,58316
2,NaN,Algeria,28.03390,1.659600,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,3,5,12,12,17,17,19,20,20,20,24,26,37,48,54,60,74,87,90,139,201,230,264,302,367,409,454,511,584,716,847,986,1171,1251,1320,1423,1468,1572,1666,1761,1825,1914,1983,2070,2160,2268,2418,2534,2629,2718,2811,2910,3007,3127,3256,3382,3517,3649,3848,4006,4154,4295,4474,4648,4838,4997,5182,5369,5558,5723,5891,6067,6253,6442,6629,6821,7019,7201,7377,7542,7728,7918,8113,8306,8503,8697,8857,8997,9134,9267,9394,9513,9626,9733,9831,9935,10050,10154,10265,10382,10484,10589,10698,10810,10919,11031,11147,11268,11385,11504,11631,11771,11920,12076,12248,12445,12685,12968,13273,13571,13907,14272,14657,15070,15500,15941,16404,16879,17348,17808,18242,18712,19195,19689,20216,20770,21355,21948,22549,23084,23691,24278,24872,25484,26159,26764,27357,27973,28615,29229,29831,30394,30950,31465,31972,32504,33055,33626,34155,34693,35160,35712,36204,36699,37187,37664,38133,38583,39025,39444,39847,40258,40667,41068,41460,41858,42228,42619,43016,43403,43781,44146,44494,44833,45158,45469,45773,46071,46364,46653,46938,47216,47488,47752,48007,48254,48496,48734,48966,49194,49413,49623,49826,50023,50214,50400,50579,50754,50914,51067,51213,51368,51530,51690,51847,51995,52136,52270,52399,52520,52658,52804,52940,53072,53325,53399,53584,53777,53998,54203,54402,54616,54829,55081,55357,55630,55880,56143,56419,56706,57026,57332,57651,57942,58272,58574,58979,59527,60169,60800,61381,62051,62693,63446,64257,65108,65975,66819,67679,68589,69591,70629,71652,72755,73774,74862,75867,77000,78025,79110,80168,81212,82221,83199,84152,85084,85927,86730,87502,88252,88825,89416,90014,90579,91121,91638,92102,92597,93065,93507,93933,94371,94781,95203,95659,96069,96549,97007,97441,97857,98249,98631,98988,99311,99610,99897
3,NaN,Andorra,42.50630,1.521800,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,2,39,39,53,75,88,113,133,164,188,224,267,308,334,370,376,390,428,439,466,501,525,545,564,583,601,601,638,646,659,673,673,696,704,713,717,717,723,723,731,738,738,743,743,743,745,745,747,748,750,751,751,752,752,754,755,755,758,760,761,761,761,761,761,761,762,762,762,762,762,763,763,763,763,764,764,764,765,844,851,852,852,852,852,852,852,852,852,853,853,853,853,854,854,855,855,855,855,855,855,855,855,855,855,855,855,855,855,855,855,855,855,855,855,855,855,855,855,855,858,861,862,877,880,880,880,884,884,889,889,897,897,897,907,907,918,922,925,925,925,937,939,939,944,955,955,955,963,963,977,981,989,989,989,1005,1005,1024,1024,1045,1045,1045,1060,1060,1098,1098,1124,1124,1124,1176,1184,1199,1199,1215,1215,1215,1261,1261,1301,1301,1344,1344,1344,1438,1438,1483,1483,1564,1564,1564,1681,1681,1753,1753,1836,1836,1836,1966,1966,2050,2050,2110,2110,2110,2370,2370,2568,2568,2696,2696,2696,2995,2995,3190,3190,3377,3377,3377,3623,3623,3811,3811,4038,4038,4038,4325,4410,4517,4567,4665,4756,4825,4888,4910,5045,5135,5135,5319,5383,5437,5477,5567,5616,5725,5725,5872,5914,5951,6018,6066,6142,6207,6256,6304,6351,6428,6534,6610,6610,6712,6745,6790,6842,6904,6955,7005,7050,7084,7127,7162,7190,7236,7288,7338,7382,7382,7446,7466,7519,7560,7577,7602,7633,7669,7699,7756,7806,7821,7875,7919,7983,8049,8117
4,NaN,Angola,-11.20270,17.873900,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,2,2,3,3,3,4,4,5,7,7,7,8,8,8,10,14,16,17,19,19,19,19,19,19,19,19,19,19,24,24,24,24,25,25,25,25,26,27,27,27,27,30,35,35,35,36,36,36,43,43,45,45,45,45,48,48,48,48,50,52,52,58,60,61,69,70,70,71,74,81,84,86,86,86,86,86,86,88,91,92,96,113,118,130,138,140,142,148,155,166,172,176,183,186,189,197,212,212,259,267,276,284,291,315,328,346,346,346,386,386,396,458,462,506,525,541,576,607,638,687,705,749,779,812,851,880,916,932,950,1000,1078,1109,1148,1164,1199,1280,1344,1395,1483,1538,1572,1672,1679,1735,1762,1815,1852,1879,1906,1935,1966,2015,2044,2068,2134,2171,2222,2283,2332,2415,2471,2551,2624,2654,2729,2777,2805,2876,2935,2965,2981,3033,3092,3217,3279,3335,3388,3439,3569,3675,3789,3848,3901,3991,4117,4236,4363,4475,4590,4672,4718,4797,4905,4972,5114,5211,5370,5402,5530,5725,5725,5958,6031,6246,6366,6488,6680,6846,7096,7222,7462,7622,7829,8049,8338,8582,8829,9026,9381,9644,9871,10074,10269,10558,10805,11035,11228,11577,11813,12102,12223,12335,12433,12680,12816,12953,13053,13228,13374,13451,13615,13818,13922,14134,14267,14413,14493,14634,14742,14821,14920,15008,15087,15103,15139,15251,15319,15361,15493,15536,15591,15648,15729,15804,15925,16061,16161,16188,16277,16362,16407,16484,16562,16626,16644,16686,16802,16931,17029,17099,17149,17240,17296,17371,17433,17553,17568

# Un-Pivoting the data

In [25]:
data_confirmed2 = pd.melt(data_confirmed, id_vars=['Province/State', 'Country/Region', 'Lat', 'Long'], 
                              var_name=['Date'],value_name='value')
data_death2 = pd.melt(data_death, id_vars=['Province/State', 'Country/Region', 'Lat', 'Long'], 
                           var_name=['Date'])
data_recovered2 = pd.melt(data_recovered, id_vars=['Province/State', 'Country/Region', 'Lat', 'Long'], 
                              var_name=['Date'])


print("The Shape of Confirmed is: ", data_confirmed2.shape)
print("The Shape of deaths is: ", data_death2.shape)
print("The Shape of recovered is: ", data_recovered2.shape)


data_confirmed2.head()

The Shape of Confirmed is:  (93766, 6)
The Shape of deaths is:  (93766, 6)
The Shape of recovered is:  (88576, 6)

  Province/State Country/Region       Lat       Long     Date  value
0            NaN    Afghanistan  33.93911  67.709953  1/22/20      0
1            NaN        Albania  41.15330  20.168300  1/22/20      0
2            NaN        Algeria  28.03390   1.659600  1/22/20      0
3            NaN        Andorra  42.50630   1.521800  1/22/20      0
4            NaN         Angola -11.20270  17.873900  1/22/20      0

# Converting the new column to dates

In [26]:
data_confirmed2['Date']=pd.to_datetime(data_confirmed2['Date'])
data_death2['Date']=pd.to_datetime(data_death2['Date'])
data_recovered2['Date']=pd.to_datetime(data_recovered2['Date'])

In [27]:
data_confirmed2.head()

  Province/State Country/Region       Lat       Long       Date  value
0            NaN    Afghanistan  33.93911  67.709953 2020-01-22      0
1            NaN        Albania  41.15330  20.168300 2020-01-22      0
2            NaN        Algeria  28.03390   1.659600 2020-01-22      0
3            NaN        Andorra  42.50630   1.521800 2020-01-22      0
4            NaN         Angola -11.20270  17.873900 2020-01-22      0

# Renaming column name

In [33]:
data_confirmed2.rename(columns={'value':'confirmed'},inplace=True)
data_death2.rename(columns={'value':'death'},inplace=True)
data_recovered2.rename(columns={'value':'recovered'},inplace=True)
data_confirmed2.head()

  Province/State Country/Region       Lat       Long       Date  confirmed
0            NaN    Afghanistan  33.93911  67.709953 2020-01-22          0
1            NaN        Albania  41.15330  20.168300 2020-01-22          0
2            NaN        Algeria  28.03390   1.659600 2020-01-22          0
3            NaN        Andorra  42.50630   1.521800 2020-01-22          0
4            NaN         Angola -11.20270  17.873900 2020-01-22          0

# Investigating NULL values

In [30]:
data_confirmed2.isna().sum().to_frame("# missing value")

                # missing value
Province/State            65048
Country/Region                0
Lat                         346
Long                        346
Date                          0
value                         0

# Dealing with Null values

In [39]:
data_confirmed2.dropna(subset=['Lat','Long'],inplace=True)
data_death2.dropna(subset=['Lat','Long'],inplace=True)
data_recovered2.dropna(subset=['Lat','Long'],inplace=True)

data_confirmed2['Province/State'].fillna(data_confirmed2['Country/Region'], inplace=True)
data_death2['Province/State'].fillna(data_death2['Country/Region'], inplace=True)
data_recovered2['Province/State'].fillna(data_recovered2['Country/Region'], inplace=True)

In [43]:
data_recovered2.isna().sum().to_frame("# missing values")

                # missing values
Province/State                 0
Country/Region                 0
Lat                            0
Long                           0
Date                           0
recovered                      0

# printing shapes before the join

In [54]:
print(data_confirmed2.shape)
print(data_recovered2.shape)
print(data_death2.shape)

(93420, 6)
(88576, 6)
(93420, 6)

In [55]:
full_join = data_confirmed2.merge(data_death2[['Province/State','Country/Region','Date','death']],
                                  how="left",
                                  left_on=['Province/State','Country/Region','Date'],
                                  right_on=['Province/State','Country/Region','Date'])
full_join.head()

,Province/State,Country/Region,Lat,Long,Date,confirmed,death
0,Afghanistan,Afghanistan,33.93911,67.709953,2020-01-22,0,0
1,Albania,Albania,41.15330,20.168300,2020-01-22,0,0
2,Algeria,Algeria,28.03390,1.659600,2020-01-22,0,0
3,Andorra,Andorra,42.50630,1.521800,2020-01-22,0,0
4,Angola,Angola,-11.20270,17.873900,2020-01-22,0,0

In [56]:
full_join = full_join.merge(data_recovered2[['Province/State','Country/Region','Date','recovered']],
                                  how="left",
                                  left_on=['Province/State','Country/Region','Date'],
                                  right_on=['Province/State','Country/Region','Date'])
full_join.head()

,Province/State,Country/Region,Lat,Long,Date,confirmed,death,recovered
0,Afghanistan,Afghanistan,33.93911,67.709953,2020-01-22,0,0,0.0
1,Albania,Albania,41.15330,20.168300,2020-01-22,0,0,0.0
2,Algeria,Algeria,28.03390,1.659600,2020-01-22,0,0,0.0
3,Andorra,Andorra,42.50630,1.521800,2020-01-22,0,0,0.0
4,Angola,Angola,-11.20270,17.873900,2020-01-22,0,0,0.0

# Adding Month and Year as a new Column

In [63]:
full_join['Month-Year'] = full_join['Date'].dt.strftime('%b-%Y')
full_join.head()

,Province/State,Country/Region,Lat,Long,Date,confirmed,death,recovered,Month-Year
0,Afghanistan,Afghanistan,33.93911,67.709953,2020-01-22,0,0,0.0,Jan-2020
1,Albania,Albania,41.15330,20.168300,2020-01-22,0,0,0.0,Jan-2020
2,Algeria,Algeria,28.03390,1.659600,2020-01-22,0,0,0.0,Jan-2020
3,Andorra,Andorra,42.50630,1.521800,2020-01-22,0,0,0.0,Jan-2020
4,Angola,Angola,-11.20270,17.873900,2020-01-22,0,0,0.0,Jan-2020

In [72]:
full_join.groupby(['Date']).sum()

                   Lat         Long  confirmed    death   recovered
Date
2020-01-22  5620.81645  6328.604714        555       17        28.0
2020-01-23  5620.81645  6328.604714        654       18        30.0
2020-01-24  5620.81645  6328.604714        941       26        36.0
2020-01-25  5620.81645  6328.604714       1434       42        39.0
2020-01-26  5620.81645  6328.604714       2118       56        52.0
2020-01-27  5620.81645  6328.604714       2927       82        61.0
2020-01-28  5620.81645  6328.604714       5578      131       107.0
2020-01-29  5620.81645  6328.604714       6167      133       126.0
2020-01-30  5620.81645  6328.604714       8235      171       143.0
2020-01-31  5620.81645  6328.604714       9927      213       222.0
2020-02-01  5620.81645  6328.604714      12038      259       284.0
2020-02-02  5620.81645  6328.604714      16787      362       472.0
2020-02-03  5620.81645  6328.604714      19887      426       623.0
2020-02-04  5620.81645  6328.604714      23898      492       852.0
2020-02-05  5620.81645  6328.604714      27643      564      1124.0
2020-02-06  5620.81645  6328.604714      30803      634      1487.0
2020-02-07  5620.81645  6328.604714      34396      719      2011.0
2020-02-08  5620.81645  6328.604714      37130      806      2616.0
2020-02-09  5620.81645  6328.604714      40160      906      3244.0
2020-02-10  5620.81645  6328.604714      42769     1013      3946.0
2020-02-11  5620.81645  6328.604714      44811     1113      4683.0
2020-02-12  5620.81645  6328.604714      45229     1118      5149.0
2020-02-13  5620.81645  6328.604714      60382     1371      6294.0
2020-02-14  5620.81645  6328.604714      66909     1523      8057.0
2020-02-15  5620.81645  6328.604714      69051     1666      9394.0
2020-02-16  5620.81645  6328.604714      71235     1770     10864.0
2020-02-17  5620.81645  6328.604714      73270     1868     12582.0
2020-02-18  5620.81645  6328.604714      75152     2008     14351.0
2020-02-19  5620.81645  6328.604714      75652     2123     16120.0
2020-02-20  5620.81645  6328.604714      76212     2248     18176.0
...                ...          ...        ...      ...         ...
2020-12-03  5620.81645  6328.604714   65295901  1506305  41612833.0
2020-12-04  5620.81645  6328.604714   65976635  1518704  42097901.0
2020-12-05  5620.81645  6328.604714   66619531  1528903  42530885.0
2020-12-06  5620.81645  6328.604714   67158883  1536100  42840134.0
2020-12-07  5620.81645  6328.604714   67673983  1544592  43242107.0
2020-12-08  5620.81645  6328.604714   68311466  1556866  43677235.0
2020-12-09  5620.81645  6328.604714   68980959  1569344  44097418.0
2020-12-10  5620.81645  6328.604714   70475012  1581982  44581030.0
2020-12-11  5620.81645  6328.604714   71174061  1594878  45052775.0
2020-12-12  5620.81645  6328.604714   71797065  1605103  46553726.0
2020-12-13  5620.81645  6328.604714   72345665  1612487  46941369.0
2020-12-14  5620.81645  6328.604714   72870090  1621452  40942830.0
2020-12-15  5620.81645  6328.604714   73494523  1635415  41294937.0
2020-12-16  5620.81645  6328.604714   74228314  1648970  41650800.0
2020-12-17  5620.81645  6328.604714   74964738  1662217  42017020.0
2020-12-18  5620.81645  6328.604714   75682346  1674862  42327671.0
2020-12-19  5620.81645  6328.604714   76298722  1685526  42676841.0
2020-12-20  5620.81645  6328.604714   76832514  1693205  42944997.0
2020-12-21  5620.81645  6328.604714   77374467  1702596  43278601.0
2020-12-22  5620.81645  6328.604714   78020935  1717055  43631745.0
2020-12-23  5620.81645  6328.604714   78712532  1730663  43949625.0
2020-12-24  5620.81645  6328.604714   79384025  1742301  44263648.0
2020-12-25  5620.81645  6328.604714   79851560  1750628  44553730.0
2020-12-26  5620.81645  6328.604714   80364189  1757722  44959622.0
2020-12-27  5620.81645  6328.604714   80797109  1764955  45236940.0
2020-12-28  5620.81645  6328.604714   81285840  1774390  45520997.0
2020-12-29  5620.81645  6328.604714   81951528  1789915  45865991.0
2020-12-30  5620.81645  6328.604714   82708267  1805008  46241311.0
2020-12-31  5620.81645  6328.604714   83424433  1818116  46516411.0
2021-01-01  5620.81645  6328.604714   83963759  1827540  46794641.0

[346 rows x 5 columns]

In [73]:
full_join.to_csv('CoronaVirus.csv')